update question set past_title = "Quelle a été la durée de vie commune avec l'autre parent (coparent)?" where question_id = 'B03';
update question set past_title = "Durant la vie commune, arrivait-il que l'autre parent présente à votre entourage une vision négative de vos compétences parentales?" where question_id = 'H06a';
update question set past_title = "Quel âge a l'enfant qui fait l'objet de l'analyse ?" where question_id = 'B06';
update question set past_title = "Depuis combien de temps êtiez-vous séparé.e de l'autre parent (coparent)?" where question_id = 'B04';
update question set past_title = "Quelle était votre situation familiale?" where question_id = 'B07';
update question set past_title = "Quelle était la situation familiale de l'autre parent?" where question_id = 'B08';
update question set past_title = "Dans quelle mesure l'entente de garde et/ou les droits d'accès étaient-ils respectés?" where question_id = 'B11';
update question set past_title = "Un jugement concernant la garde des enfants avait-il été rendu par le tribunal ?" where question_id = 'B11a';
update question set past_title = "L'autre parent (coparent) respectait-il les ordonnances ou les jugements de la Cour ?" where question_id = 'B11a1';
update question set past_title = "Respectiez-vous, de votre côté, les ordonnances et entente de garde ?" where question_id = 'B11b';
update question set past_title = "Aviez-vous encore un lien et/ou des contacts avec votre enfant?" where question_id = 'B11c';
update question set past_title = "Quels types de difficultés relationnelles rencontriez-vous ?" where question_id = 'B11c1';
update question set past_title = "Ces difficultés relationnelles étaient-elles récentes?" where question_id = 'B11c2';
update question set past_title = "Y avait-il d'autres enfants en rupture de lien ou de contact?" where question_id = 'B11c3';
update question set past_title = "Un traumatisme vécu par vous, par l'autre parent ou par l'enfant aurait-il pu expliquer la rupture de contact ou de lien avec votre enfant ?" where question_id = 'B11c5';
update question set past_title = "Durant la vie commune avec l'autre parent (coparent), quel était le degré de complicité entre vous et votre enfant?" where question_id = 'H01';
update question set past_title = "Durant la vie commune avec l'autre parent, dans quelle mesure diriez-vous que votre enfant se confiait naturellement à vous pour ses questionnements, peines et chagrins ou pour partager de bonnes nouvelles?" where question_id = 'H02';
update question set past_title = "Dans quelle mesure diriez-vous que votre enfant idéalisait l’autre parent avant la séparation (éclatement de la famille)?" where question_id = 'H03';
update question set past_title = "Comment qualifieriez-vous la complicité entre votre enfant et l'autre parent avant la séparation (éclatement de votre famille)?" where question_id = 'H04';
update question set past_title = "Durant la vie commune, dans quelle mesure diriez-vous que la relation entre votre enfant et l'autre parent était fusionnelle?" where question_id = 'H04a';
update question set past_title = "Durant la vie commune, arrivait-il que l'autre parent vous critique ou vous dénigre devant votre enfant ?" where question_id = 'H05';
update question set past_title = "Durant la vie commune, arrivait-il que l'autre parent hausse le ton ou vous insulte (injure) pour imposer son point de vue ou sa volonté ?" where question_id = 'H05a';
update question set past_title = "Dans quelle mesure êtes-vous d'accord avec l'énoncé suivant? Durant la vie commune l'autre parent percevait votre rôle parental comme étant aussi important que le sien." where question_id = 'H06';

update question set past_title = "Dans quelle mesure deviez-vous faire  des compromis pour assurer une bonne entente de garde ?" where question_id = 'PCR02';
update question set past_title = "Dans quelle mesure vous arrivait-il d'éviter ou d'ignorer l’autre parent lorsque vous le croisiez à l'école, lors de changement de garde ou lors d'événements sportifs ?" where question_id = 'PCR03';
update question set past_title = "Dans quelle mesure questionniez-vous votre enfant à son retour de garde afin de connaître la routine (repas, dodo, etc.) et les activités qu'il avait fait alors qu'il était chez l'autre parent?" where question_id = 'PCR04';
update question set past_title = "Dans quelle mesure deviez-vous faire un retour sur les interventions (nutrition, hygiène, logistique, etc.) de l'autre parent (par courriel ou texto) au retour des enfants après un séjour de garde?" where question_id = 'PCR06';
update question set past_title = "Quels étaient les sujets de discorde entre vous et l'autre parent?" where question_id = 'PCR06a';
update question set past_title = "Vous arrivait-il de faire des reproches à l'autre parent devant votre enfant ?" where question_id = 'PCR07';
update question set past_title = "À quelle fréquence appeliez-vous votre enfant lorsqu’il était chez l‘autre parent ?" where question_id = 'PCR08';
update question set past_title = "Dans quelle mesure laissiez-vous à votre enfant le droit de choisir la fréquence des visites et le temps qu'il passait chez l'autre parent ?" where question_id = 'PCR09';
update question set past_title = "Dans quelle mesure considériez-vous l'autre parent (coparent) comme étant votre égal·e sur le plan parental?" where question_id = 'PCR01';
update question set past_title = "De manière générale, au-delà des conflits qui pouvaient vous opposer à l'autre parent, dans quelle mesure diriez-vous que les exigences de la coparentalité nuisait à votre qualité de vie?" where question_id = 'PCR10';
update question set past_title = "Dans quelle mesure acceptiez-vous que les vêtements et/ou jouets de votre enfant se promènent d’une maison à l’autre ?" where question_id = 'PCR11';
update question set past_title = "Dans quelle mesure vous arrivait-il de prendre des décisions sans consulter l'autre parent ?" where question_id = 'PCR12';
update question set past_title = "Quel type de décisions avez-vous pris sans consulter l'autre parent ou sans attendre son approbation ?" where question_id = 'PCR12a';
update question set past_title = "Dans quelle mesure diriez-vous que la mauvaise entente entre vous et l'autre parent vous contraignait à demander à votre enfant de faire les messages et demandes entourant la logistique familiale?" where question_id = 'PCR13';
update question set past_title = "Dans quelle mesure étiez-vous d'accord ou non avec cet énoncé? Un enfant de 12 ans est assez mature pour choisir où et avec qui il veut vivre." where question_id = 'PCR14';
update question set past_title = "Dans quelle mesure diriez-vous qu'il était important que votre enfant soit au courant des enjeux de la séparation et/ou du conflit qui vous opposait à l'autre parent?" where question_id = 'PCR15';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Vous aviez mis votre enfant au courant des enjeux juridiques (pension alimentaire, modalité de garde, etc.) qui vous opposait à l’autre parent." where question_id = 'PCR15a';
update question set past_title = "Au-delà des conflits, dans quelle mesure acceptiez-vous et êtiez-vous serein·e avec la séparation (séparation de couple ou familiale)?" where question_id = 'PCR16';
update question set past_title = "Dans quelle mesure diriez-vous que vous confiiez à votre enfant votre peine concernant la séparation?" where question_id = 'PCR16a';
update question set past_title = "Au retour d’un séjour chez l’autre parent, il arrivait à votre enfant d'être agressif envers vous et de vous accabler de reproches. Comment réagissiez-vous ?" where question_id = 'PCR17';
update question set past_title = "Si votre enfant vous accusait de mentir, de voler l'argent de l'autre parent, etc. Comment réagissiez-vous ?" where question_id = 'PCR18';

update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? L'autre parent (coparent) devait faire des compromis pour assurer une bonne entente de garde." where question_id = 'PFA00';
update question set past_title = "Comment qualifieriez-vous (retrospectivement) la relation et le degré de complicité (ou alliance) entre votre enfant et l'autre parent?" where question_id = 'PFA01';
update question set past_title = "Selon vous, dans quelle mesure l'autre parent entretenait une relation fusionnelle avec votre enfant ?" where question_id = 'PFA02';
update question set past_title = "Diriez-vous que la relation fusionnelle entre votre enfant et l'autre parent était consciente (intentionnelle) ou inconsciente?" where question_id = 'PFA02a';
update question set past_title = "Selon vous, dans quelle mesure l’autre parent demandait à votre enfant de garder des secrets et de vous cacher des choses?" where question_id = 'PFA03';
update question set past_title = "Quelle est la probabilité de l'énoncé suivant? L’autre parent laissait entendre à votre enfant que vous aviez abandonné la famille." where question_id = 'PFA04';
update question set past_title = "Quelle est la probabilité de l'énoncé suivant? L’autre parent laissait entendre à votre enfant que vous ne l’aimiez pas vraiment." where question_id = 'PFA04a';
update question set past_title = "Quelle est la probabilité de l'énoncé suivant? L’autre parent laissait entendre à votre enfant que vous souffriez d’une maladie mentale ou que vous êtiez instable psychologiquement." where question_id = 'PFA05';
update question set past_title = "Quelle est la probabilité de l'énoncé? L'autre parent laissait entendre à votre enfant qu’il ou elle n’était pas en sécurité avec vous." where question_id = 'PFA05a';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent modifiait certains faits (historiques) concernant votre passé à son avantage ou à votre désavantage?" where question_id = 'PFA06';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? L'autre parent déformait les souvenirs de votre enfant (ex.: souvenirs heureux de la petite enfance vus aujourd'hui négativement)." where question_id = 'PFA06a';
update question set past_title = "Quelle est la probabilité de l'énoncé suivant ?  L’autre parent culpabilisait votre enfant de sa relation ou de son amour pour vous?" where question_id = 'PFA07';
update question set past_title = "Arrivait-il que l’autre parent boude votre enfant ou se fâche lorsqu'il était temps de rentrer chez vous (à votre tour de garde)?" where question_id = 'PFA07a';
update question set past_title = "Arrivait-il à l’autre parent de se fâcher contre votre enfant lorsqu'il ou elle exprimait de l'affection pour vous?" where question_id = 'PFA07a1';
update question set past_title = "Arrivait-il que l'autre parent vous accable de reproches par courriel ou texto au retour des enfants (après un séjour chez vous)?" where question_id = 'PFA09';
update question set past_title = "Dans quelle mesure l'autre parent faisait ou avait déjà fait des menaces (claires ou voilées) de vous enlever les enfants?" where question_id = 'PFA09a';
update question set past_title = "Arrivait-il à l’autre parent de vous ignorer lorsqu’il ou elle vous croisait à l’école, ou lors des changements de garde ou d'événements sportifs?" where question_id = 'PFA10';
update question set past_title = "L'autre parent était d'avis que votre enfant était assez mature pour choisir où et avec qui il voulait vivre ?" where question_id = 'PFA11';
update question set past_title = "Dans quelle mesure cet énoncé s'applique-t-il selon vous? L'autre parent vous demandait de respecter les désirs et choix de votre enfant." where question_id = 'PFA11a';
update question set past_title = "Dans quelle mesure cet énoncé s'applique-t-il selon vous? L'autre parent questionnait votre enfant à son retour de garde sur les activités qu'il a fait alors qu'il était chez vous." where question_id = 'PFA12';
update question set past_title = "Arrivait-il que l’autre parent vous dénigre en la présence de votre enfant ?" where question_id = 'PFA13';
update question set past_title = "Dans quelle mesure cet énoncé s'applique-t-il selon vous? L'autre parent vous renvoyait une image négative de vous-même en tant que parent, ridiculisait vos décisions ou vous insultait?" where question_id = 'PFA13a';
update question set past_title = "Dans quelle mesure l'autre parent faisait ou avait déjà fait des menaces (claires ou voilées) de vous enlever les enfants?" where question_id = 'PFA13b';
update question set past_title = "Dans quelle mesure l'autre parent présentait aux autres une vision négative de vos comportements ou de votre santé mentale et compétences parentales?" where question_id = 'PFA13c';
update question set past_title = "Arrivait-il que l’autre parent dénigre ouvertement votre nouvelle famille devant votre enfant? (dénigrement du nouveau ou nouvelle conjoint·e et/ou enfant(s) né(s) d’une nouvelle union)" where question_id = 'PFA14';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent laissait entendre qu'il ou elle représentait la 'vraie' famille de votre enfant?" where question_id = 'PFA15';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent demandait à ce que votre enfant appelle le nouveau ou nouvelle conjoint·e maman ou papa ?" where question_id = 'PFA15a';
update question set past_title = "Évaluez la fréquence de l'énoncé : l'autre parent vous imposait des changements d’horaires sans vous consulter au préalable et sans votre autorisation." where question_id = 'PFA16';
update question set past_title = "Évaluez l'intensité et la fréquence de l'énoncé : l'autre parent ramènait votre enfant à la maison à l'heure qui lui convenait (sans respecter l'entente initiale)." where question_id = 'PFA16a';
update question set past_title = "Évaluez la fréquence de l'énoncé : l’autre parent organisait et proposait des activités à votre enfant sur votre temps de garde." where question_id = 'PFA16b';
update question set past_title = "Arrivait-il que l’autre parent organise des activités amusantes, voire irrésistibles à votre enfant alors que c’était votre week-end ou votre semaine avec votre enfant?" where question_id = 'PFA16b1';
update question set past_title = "Évaluez la fréquence de l'énoncé : l’autre parent se présentait à la sortie des classes, au service de garde ou à la garderie sur votre temps de garde." where question_id = 'PFA17';
update question set past_title = "Évaluez la fréquence et l'intensité de l'énoncé : l’autre parent imposait sa présence en appelant (ou en textant) régulièrement votre enfant durant votre temps de garde." where question_id = 'PFA18';
update question set past_title = "Dans quelle mesure l'autre parent vous communiquait les informations médicales, scolaires ou liées aux activités sociales ou sportives de votre enfant?" where question_id = 'PFA19';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent interdisait aux personnes gravitant autour de votre enfant (professeurs, éducateurs, medecins, entraîneurs, etc.) de vous communiquer de l'information à son sujet?" where question_id = 'PFA19a';
update question set past_title = "Dans quelle mesure était-il facile de communiquer avec votre enfant lorsqu’il était chez l’autre parent?" where question_id = 'PFA20';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent contrôlait, écoutait ou écourtait vos conversations téléphoniques avec votre enfant (lorsque chez l’autre parent)?" where question_id = 'PFA20a';
update question set past_title = "Arrivait-il que l'autre parent se présente à votre domicile sans s'annoncer ou sans invitation?" where question_id = 'PFA20b';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent vous considérait comme étant son égal·e sur le plan parental?" where question_id = 'PFA21';
update question set past_title = "Dans quelle mesure cet énoncé s'applique-t-il selon vous? L'autre parent sentait qu’il était en compétition avec vous pour l’amour de votre enfant?" where question_id = 'PFA21a';
update question set past_title = "Dans quelle mesure cet énoncé s'applique-t-il selon vous? L'autre parent estimait que les exigences de la coparentalité (logistique horaire, transport, compromis vacances, etc.) nuisait à sa qualité de vie." where question_id = 'PFA22';
update question set past_title = "Dans quelle mesure diriez-vous que l'identité et la valeur sociale de l'autre parent passait par sa paternité ou sa maternité?" where question_id = 'PFA23';
update question set past_title = "Quelle est la probabilité de l'énoncé : l’autre parent cherchait à vous blesser ou à se venger parce que vous aviez brisé ou abandonné la famille?" where question_id = 'PFA24';
update question set past_title = "Dans quelle mesure l'autre parent vous appelait par votre prénom devant votre enfant (plutôt que maman ou papa)?" where question_id = 'PFA25';
update question set past_title = "Cette façon de s'adresser à vous devant votre enfant (prénom versus maman ou papa), était-elle habituelle ou était-ce nouveau depuis la séparation?" where question_id = 'PFA25a';
update question set past_title = "Dans quelle mesure cet énoncé s'appliquait-il selon vous? L’autre parent considérait son nouveau ou nouvelle conjoint·e comme étant un meilleur parent que vous." where question_id = 'PFA26';
update question set past_title = "Dans quelle mesure diriez-vous que l’autre parent cherchait à limiter les contacts entre votre enfant et votre famille élargie (cousin.es, oncles, tantes, grands-parents, etc.)?" where question_id = 'PFA27';
update question set past_title = "Dans quelle mesure cet énoncé s'apliquait à votre situation? L’autre parent permettait à votre enfant d'apporter des objets (jouets ou objets symboliques) ou cadeaux reçus provenant de chez vous?" where question_id = 'PFA28';
update question set past_title = "Dans quelle mesure diriez-vous que l’autre parent jette les cadeaux (anniveraire, Noël) ou proscrit les photographies de vous dans sa demeure ?" where question_id = 'PFA28a';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent se disait impuissant et non responsable de la décision de votre enfant de ne plus respecter l'entente de garde?" where question_id = 'PFA29';
update question set past_title = "Quelles décisions ont été prises sans votre consentement ou connaissance de votre part ?" where question_id = 'PFA29a';
update question set past_title = "Étiez-vous déchu·e (totalement ou en partie) de votre autorité parentale ?" where question_id = 'PFA29b';
update question set past_title = "Dans quelle mesure diriez-vous que l’autre parent forçait votre enfant à choisir entre ses deux parents?" where question_id = 'PFA30';
update question set past_title = "Dans quelle mesure diriez-vous que l’autre parent cherchait à vous exclure de la vie de votre enfant?" where question_id = 'PFA30a';
update question set past_title = "Dans quelle mesure l'autre parent faisait ou avait déjà fait des menaces (claires ou voilées) de vous enlever les enfants?" where question_id = 'PFA30a1';
update question set past_title = "Quels sont les comportements ou attitudes qui vous laissent croire que l'autre parent cherchait à vous exclure de la vie de votre enfant?" where question_id = 'PFA30a2';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent acceptait ou vivait bien avec la séparation (séparation de couple ou familiale)?" where question_id = 'PFA31';
update question set past_title = "Dans quelle mesure diriez-vous que l’autre parent confiait à votre enfant sa peine concernant la séparation?" where question_id = 'PFA31a';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent se confiait à votre enfant sur des sujets qui vous étaient personnels ou concernent votre passé (intime)?" where question_id = 'PFA31a1';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? L'autre parent faisait lire vos échanges et communications (textos, messenger, courriels) à votre enfant." where question_id = 'PFA32';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent encourageait ou entretenait un discours dénigrant ou haineux à l’égard de votre nouveau ou nouvelle conjoint·e?" where question_id = 'PFA33';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent  refusait de vous parler et demandait à votre enfant de faire les messages et autres demandes entourant la logistique familiale?" where question_id = 'PFA34';
update question set past_title = "Dans quelle mesure l’autre parent laissait à votre enfant le droit de choisir de respecter ou non l'entente de garde et votre temps (tour) de garde?" where question_id = 'PFA35';
update question set past_title = "Dans quelle mesure diriez-vous que l'autre parent demandait à votre enfant de choisir avec quel parent il voulait vivre?" where question_id = 'PFA11';
update question set past_title = "Selon vous, quels étaient les enjeux les plus importants pour l'autre parent au niveau de la garde des enfants?" where question_id = 'PFA38';
update question set past_title = "Comment qualifieriez-vous votre relation (harmonie) et votre degré de complicité avec votre enfant?" where question_id = 'E01';
update question set past_title = "Dans quelle mesure diriez-vous que votre enfant idéalisait l’autre parent?" where question_id = 'E02';
update question set past_title = "Dans quelle mesure diriez-vous que la relation entre votre enfant et l'autre parent était fusionnelle?" where question_id = 'E02a';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant gardait des secrets et vous cachait de l'information concernant sa relation avec l'autre parent." where question_id = 'E03';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant avait reçu l’ordre de ne pas vous raconter ce qui se passe chez l’autre parent." where question_id = 'E03a';
update question set past_title = "Dans quelle mesure êtes-vous d'accord avec l'énoncé suivant? Votre enfant défendait systématiquement l'autre parent, quoi que vous fassiez, quoi que vous disiez." where question_id = 'E04';
update question set past_title = "Dans quelle mesure êtes-vous d'accord avec l'énoncé suivant? Aux yeux de votre enfant, tout ce que faisait l'autre parent était bien, voire parfait, et tout ce que vous faisiez était mauvais ou sujet à critiques." where question_id = 'E04a';
update question set past_title = "Dans quelle mesure diriez-vous que votre enfant s’exprimait avec des expressions ou des paroles empruntées à l’autre parent?" where question_id = 'E05';
update question set past_title = "Dans quels contextes ou à quelles occasions cela se produisait-il ?" where question_id = 'E05a';
update question set past_title = "Dans quelle mesure diriez-vous que votre enfant vous accusait ou vous reprochait d'avoir abandonné la famille?" where question_id = 'E06';
update question set past_title = "Évaluez la fréquence ou l'intensité de l'énoncé : votre enfant croyait que vous souffriez d’une maladie mentale ou que vous étiez instable psychologiquement." where question_id = 'E06a';
update question set past_title = "Évaluez la fréquence ou l'intensité de l'énoncé : votre enfant vous reprochait ou vous accusait d'être dangereux.se ou de présenter un danger pour sa sécurité." where question_id = 'E06a1';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant se sentait coupable de passer du temps avec vous car cela indisposait, contrariait ou faisait de la peine à l'autre parent." where question_id = 'E07';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant vous tenait responsable de la peine (détresse) de son autre parent." where question_id = 'E9';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant cherchait à vous convaincre des qualités de l’autre parent." where question_id = 'E10';
update question set past_title = "Dans quelle mesure votre enfant vous ignorait lorsqu’il ou elle était en compagnie de l'autre parent et qu'il vous croisait à l’école, lors d'événements sportifs, etc. ?" where question_id = 'E11';
update question set past_title = "Arrivait-il à votre enfant de dénigrer vos compétences parentales devant l’autre parent ?" where question_id = 'E12';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant dénigrait ouvertement votre nouvelle famille (nouveau conjoint + enfant(s) né(s) d’une nouvelle union)." where question_id = 'E13';
update question set past_title = "Dans quelle mesure votre enfant laissait entendre que sa 'vraie' famille était avec l’autre parent ?" where question_id = 'E14';
update question set past_title = "Dans quelle mesure diriez-vous que pour votre enfant, la nouvelle famille de l'autre parent (famille recomposée ou non) avait plus de valeur que la vôtre?" where question_id = 'E14a';
update question set past_title = "Évaluez l'intensité et la fréquence de l'énoncé : il arrivait à votre enfant d'être agressif envers vous à son retour d'un séjour chez l'autre parent." where question_id = 'E15';
update question set past_title = "Évaluez la fréquence et/ou l'intensité de l'énoncé : votre enfant vous accusait de voler de l’argent à son autre parent ou d'être responsable de son apauvrissement." where question_id = 'E15a';
update question set past_title = "Dans quelle mesure arrivait-il à votre enfant de demander à changer les horaires de garde et de visite à la faveur de l'autre parent?" where question_id = 'E16';
update question set past_title = "Dans quelle mesure arrivait-il à votre enfant d'imposer des changements d’horaires et de visite à la faveur de l'autre parent sans vous consulter au préalable et sans votre autorisation?" where question_id = 'E16a';
update question set past_title = "Arrivait-il à votre enfant de changer d’idée concernant une activité prévue à l’horaire avec vous? D’abord enthousiaste, il trouvait (subitement / dernières minutes) des excuses pour ne pas participer à l’activité?" where question_id = 'E16b';
update question set past_title = "Évaluez l'intensité et/ou la fréquence de l'énoncé : votre enfant subissait une pression pour passer plus de temps chez l'autre parent." where question_id = 'E16c';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant ne répondait pas à vos messages (texto, messenger, instagram, etc.) lorsqu’il était chez l’autre parent." where question_id = 'E18';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant considèrait le nouveau conjoint ou à la nouvelle conjointe comme son père ou sa mère." where question_id = 'E20';
update question set past_title = "Êtes-vous d'accord ou pas d'accord avec l'énoncé suivant? Les jouets et les vêtements de votre enfant se promènaient d’une maison à l’autre simplement." where question_id = 'E21';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? L'autre parent refusait que votre enfant apporte des objets qui proviennent de votre demeure ou de votre milieu." where question_id = 'E21a';
update question set past_title = "Dans quelle mesure diriez-vous que votre enfant connaissait des informations personnelles ou intimes de vous dont vous n'aviez jamais discuté avec lui?" where question_id = 'E22';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Les souvenirs de votre enfant vous semblaient être déformés (ex.: souvenirs heureux de la petite enfance vus aujourd'hui négativement)." where question_id = 'E22a';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant tenait le rôle de messager et avait la responsabilité de vous communiquer les informations concernant la logistique familiale (ex. : horaires école et activités sportives, gestion lunch, vêtements, etc.)." where question_id = 'E17';
update question set past_title = "Dans quelle mesure êtes-vous d'accord avec l'énoncé suivant ? Votre enfant se sentait responsable du bonheur de l’autre parent et/ou sentait le besoin de le protéger." where question_id = 'E23';
update question set past_title = "Dans quelle mesure êtes-vous d'accord avec l'énoncé suivant? L'autre parent (coparent) avait  informé votre enfant du contexte juridique, financier et autres associé au conflit vous opposant." where question_id = 'E24';
update question set past_title = "Dans quelle mesure diriez-vous que votre enfant sentait le besoin de protéger l’autre parent ou de défendre ses intérêts?" where question_id = 'E25';
update question set past_title = "Dans quelle mesure diriez-vous que le comportement et/ou l'attitude de votre enfant changeait en présence de l’autre parent ?" where question_id = 'E26';
update question set past_title = "Dans quelle mesure notiez-vous un changement au niveau du comportement de votre enfant à son retour de garde?" where question_id = 'E27';
update question set past_title = "De manière générale, au retour d'un séjour chez l'autre parent, votre enfant vous paraissait :" where question_id = 'E27a';
update question set past_title = "Évaluez la fréquence et l'intensité de l'énoncé : au retour d’un séjour chez l’autre parent, votre enfant vous questionnait sur vos décisions présentes ou passsées ou vous accablait de reproches?" where question_id = 'E27b';
update question set past_title = "Dans quelle mesure votre enfant s'isolait (ex.: chambre) ou se cachait (ex.: toilettes) pour appeler son autre parent afin qu'on n'entende pas ses conversations?" where question_id = 'E28';
update question set past_title = "Dans quelle mesure diriez-vous que votre enfant avait changé ou adapté ses champs d’intérêts pour partager de plus en plus les intérêts de l’autre parent?" where question_id = 'E29';
update question set past_title = "Évaluez la fréquence et l'intensité de l'énoncé : votre enfant rejetait de plus en plus vos valeurs et vos champs d’intérêts." where question_id = 'E29a';
update question set past_title = "Dans quelle mesure cet énoncé s'applique votre situation? Votre enfant réclamait le droit de choisir les moments où il vous rend visite et la durée des visites chez vous." where question_id = 'E30';
update question set past_title = "Évaluez la fréquence et l'intensité de l'énoncé : votre enfant calquait les désirs et les paroles de l’autre parent." where question_id = 'E31';
update question set past_title = "Évaluez la fréquence et l'intensité de l'énoncé : votre enfant vous accusait de mentir, de voler, etc." where question_id = 'E32';
update question set past_title = "Évaluez la fréquence ou l'intensité de l'énoncé : votre enfant vous reprochait de lui manquer de respect en ne respectant pas ses choix, besoins, désirs, rythme, etc." where question_id = 'E33';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant avait demandé à changer les termes de la garde afin de passer plus de temps chez l’autre parent" where question_id = 'E33a';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant vous avait annoncé qu’à 12 ou 14 ans, il ou elle pourrait choisir les modalités de garde et vivre là où bon lui semble" where question_id = 'E33b';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre enfant vous avait bloqué des réseaux sociaux (cell/texto, messenger, instagram)." where question_id = 'E34';
update question set past_title = "Dans quelle mesure diriez-vous que votre enfant refusait les contacts avec votre famille élargie (grands-parents, cousin.es, etc.)?" where question_id = 'E35';
update question set past_title = "Comment était la relation de votre enfant avec la famille élargie avant la séparation?" where question_id = 'E35a';
update question set past_title = "Est-ce que votre enfant présentait des troubles psychosomatiques?" where question_id = 'E36';
update question set past_title = "Quelles étaient les manifestations ou troubles psychosomatiques présents chez votre enfant et à quelle fréquence?" where question_id = 'E36a';
update question set past_title = "Lesquelles de ces manifestations étaient déjà apparentes avant la séparation et à quelle fréquence?" where question_id = 'E36b';
update question set past_title = "Dans quelle mesure êtes-vous d'acord avec l'énoncé suivant ? Le nouveau ou nouvelle conjoint·e jouait un rôle de confident·e auprès de votre enfant ?" where question_id = 'NC01';
update question set past_title = "Dans quelle mesure cette relation de confident.e vous apparaissait être malsaine?" where question_id = 'NC01a';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Le nouveau ou nouvelle conjoint·e laissait entendre à votre enfant qu’il ou elle n’était pas en sécurité avec vous." where question_id = 'NC02';
update question set past_title = "Dans quelle mesure le nouveau ou nouvelle conjoint·e vous ignorait lorsqu’il vous croisait à l’école, lors des changements de garde ou lors d'événements sportifs?" where question_id = 'NC03';
update question set past_title = "Dans quelle mesure arrivait-il que le nouveau ou nouvelle conjoint·e vous critique ou dénigre vos compétences parentales devant votre enfant ?" where question_id = 'NC04';
update question set past_title = "Dans quelle mesure le nouveau ou nouvelle conjoint·e dénigrait vos compétences parentales par texto, courriel ou autres?" where question_id = 'NC05';
update question set past_title = "Évaluez l'intensité de l'énoncé : le nouveau ou nouvelle conjoint·e dénigrait ouvertement votre nouvelle famille devant votre enfant (nouveau conjoint + enfants nés ou non d’une nouvelle union)" where question_id = 'NC06';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Il arrivait que le nouveau ou nouvelle conjoint·e apporte des changements à l’horaire de garde (se substituant à l'autorité de l'autre parent) sans vous consulter au préalable, et sans votre autorisation." where question_id = 'NC07';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Le nouveau ou nouvelle conjoint·e organisait des activités sur votre temps de garde?" where question_id = 'NC08';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Le nouveau ou nouvelle conjoint·e se présentait à la sortie des classes, au service de garde ou à la garderie sur votre temps de garde." where question_id = 'NC09';
update question set past_title = "Lorsque vous appeliez votre enfant chez l'autre parent, arrivait-il que le nouveau ou nouvelle conjoint·e interfère, écoute ou écourte vos conversations téléphoniques avec votre enfant?" where question_id = 'NC10';
update question set past_title = "Dans quelle mesure le nouveau ou nouvelle conjoint·e était responsable de la logistique familiale : communication scolaire, rendez-vous médicaux, etc.?" where question_id = 'NC11';
update question set past_title = "Évaluez la fréquence et l'intensité de l'énoncé : le nouveau ou nouvelle conjoint·e imposait sa présence en appelant (ou en textant) régulièrement votre enfant durant votre temps de garde." where question_id = 'NC12';
update question set past_title = "Dans quelle mesure le nouveau ou nouvelle conjoint·e interdisait aux personnes gravitant autour de votre enfant (professeurs, éducateurs, medecins, entraîneurs, etc.) de vous communiquer de l'information au sujet de votre enfant?" where question_id = 'NC13';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Le nouveau ou nouvelle conjoint·e demandait à votre enfant de l'appeler maman ou papa." where question_id = 'NC14';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre relation avec votre enfant s'était fragilisée depuis l'arrivée du nouveau ou nouvelle conjoint·e." where question_id = 'NC15';
update question set past_title = "Dans quelle mesure cet énoncé s'applique à votre situation? Le nouveau ou nouvelle conjoint·e vous demandait de respecter les désirs et choix de votre enfant." where question_id = 'NC16';
update question set past_title = "Êtes-vous en processus juridique actuellement?" where question_id = 'B09';
update question set past_title = "Quelles sont les modalités de garde des enfants aujourd'hui?" where question_id = 'B10';
update question set past_title = "Si vous avez répondu garde partagée (ou garde dite alternée), dans quelle proportion avez-vous la garde?" where question_id = 'B10a';
update question set past_title = "Durant l’enfance et avant 14 ans, est-ce que vous et/ou votre ex-conjoint·e (coparent) avez vécu l’une des situations familiales suivantes ? Cochez les réponses qui s'appliquent." where question_id = 'B11';
update question set past_title = "Vous étiez à l'aise en présence de l'autre parent (coparent)." where question_id = 'PCR00';
update question set past_title = "Dans quelle mesure l'autre parent haussait la voix ou utilisait des jurons pour imposer sa vision des choses?" where question_id = 'PCR00b';
update question set past_title = "Arrivait-il que l'autre parent vous accable de questions ou de reproches (harcèle) par téléphone ou par courriel?" where question_id = 'PFA20c';

