INSERT INTO question_category(
  [category_id]
  
)
 VALUES
( "N/A"),
(
  "Alliance"
),
(
  "Altération/dévoiement de la réalité"
),
(
  "Chantage affectif, loyauté, manipulation"
),
(
  "Dénigrement"
),
(
  "Interférence temps et/ou communication"
),
(
  "Interférence lien affectif ou symbolique"
),
(

  "Parentification"
),
(

  "Rôle actif, Réponse au CC, r"
);

insert into question_category_question([question_id],[category_id]) values
('B01','N / A'),
('B02','N / A'),
('B03','N / A'),
('B04','N / A'),
('B05','N / A'),
('B07','N / A'),
('B08','N / A'),
('B11','E: Interférence temps et/ou communication'),
('B11a','N / A'),
('B11a1','E: Interférence temps et/ou communication'),
('B11b','E: Interférence temps et/ou communication'),
('B11c','E: Interférence temps et/ou communication'),
('H01','A:Alliance'),
('H02','A:Alliance'),
('H03','A:Alliance'),
('H04','A:Alliance'),
('H04a','A:Alliance'),
('H05','D: Dénigrement'),
('H05a','D: Dénigrement'),
('H06','F: Interférence lien affectif ou symbolique'),
('PCR02','C: Chantage affectif, loyauté, manipulation'),
('PCR04','C: Chantage affectif, loyauté, manipulation'),
('PCR06','D: Dénigrement'),
('PCR06a','D: Dénigrement'),
('PCR07','D: Dénigrement'),
('PCR08','E: Interférence temps et/ou communication'),
('PCR09','E: Interférence temps et/ou communication'),
('PCR01','E: Interférence temps et/ou communication'),
('PCR10','F: Interférence lien affectif ou symbolique'),
('PCR11','F: Interférence lien affectif ou symbolique'),
('PCR12','F: Interférence lien affectif ou symbolique'),
('PCR12a','F: Interférence lien affectif ou symbolique'),
('PCR13','G: Parentification'),
('PCR14','G: Parentification'),
('PCR15','G: Parentification'),
('PCR15a','G: Parentification'),
('PCR16','G: Parentification'),
('PCR16a','G: Parentification'),
('PFA01','A:Alliance'),
('PFA02','A:Alliance'),
('PFA02a','A:Alliance'),
('PFA03','A:Alliance'),
('PFA04','B:Altération/dévoiement de la réalité'),
('PFA04a','B:Altération/dévoiement de la réalité'),
('PFA05','B:Altération/dévoiement de la réalité'),
('PFA05a','B:Altération/dévoiement de la réalité'),
('PFA06','B:Altération/dévoiement de la réalité'),
('PFA06a','B:Altération/dévoiement de la réalité'),
('PFA07','C: Chantage affectif, loyauté, manipulation'),
('PFA07a','C: Chantage affectif, loyauté, manipulation'),
('PFA07a1','C: Chantage affectif, loyauté, manipulation'),
('PFA09','C: Chantage affectif, loyauté, manipulation'),
('PFA09a','C: Chantage affectif et manipulation'),
('PFA10','C: Chantage affectif, loyauté, manipulation'),
('PFA11','H: Rôle actif, Réponse au CC, r'),
('PFA11a','H: Rôle actif, Réponse au CC, r'),
('PFA12','C: Chantage affectif, loyauté, manipulation'),
('PFA13','D: Dénigrement'),
('PFA13a','D: Dénigrement'),
('PFA13b','D: Dénigrement'),
('PFA13c','D: Dénigrement'),
('PFA14','D: Dénigrement'),
('PFA15','D: Dénigrement'),
('PFA15a','D: Dénigrement'),
('PFA16','E: Interférence temps et/ou communication'),
('PFA16a','E: Interférence temps et/ou communication'),
('PFA16b','E: Interférence temps et/ou communication'),
('PFA16b1','E: Interférence temps et/ou communication'),
('PFA17','E: Interférence temps et/ou communication'),
('PFA18','E: Interférence temps et/ou communication'),
('PFA19','E: Interférence temps et/ou communication'),
('PFA19a','E: Interférence temps et/ou communication'),
('PFA20','E: Interférence temps et/ou communication'),
('PFA20a','E: Interférence temps et/ou communication'),
('PFA20b','E: Interférence temps et/ou communication'),
('PFA21','F: Interférence lien affectif ou symbolique'),
('PFA21a','F: Interférence lien affectif ou symbolique'),
('PFA22','F: Interférence lien affectif ou symbolique'),
('PFA23','F: Interférence lien affectif ou symbolique'),
('PFA24','F: Interférence lien affectif ou symbolique'),
('PFA25','F: Interférence lien affectif ou symbolique'),
('PFA25a','F: Interférence lien affectif ou symbolique'),
('PFA26','F: Interférence lien affectif ou symbolique'),
('PFA27','F: Interférence lien affectif ou symbolique'),
('PFA28','F: Interférence lien affectif ou symbolique'),
('PFA28a','F: Interférence lien affectif ou symbolique'),
('PFA29','F: Interférence lien affectif ou symbolique'),
('PFA29a','F: Interférence lien affectif ou symbolique'),
('PFA29b','F: Interférence lien affectif ou symbolique'),
('PFA30','F: Interférence lien affectif ou symbolique'),
('PFA30a','F: Interférence lien affectif ou symbolique'),
('PFA30a1','F: Interférence lien affectif ou symbolique'),
('PFA30a2','F: Interférence lien affectif ou symbolique'),
('PFA31','G: Parentification'),
('PFA31a','G: Parentification'),
('PFA31a1','G: Parentification'),
('PFA32','G: Parentification'),
('PFA33','H: Rôle actif, Réponse au CC, r'),
('PFA34','H: Rôle actif, Réponse au CC, r'),
('PFA35','H: Rôle actif, Réponse au CC, r'),
('PFA11','C: Chantage affectif, loyauté, manipulation'),
('PFA38','N / A'),
('E01','A:Alliance'),
('E02','A:Alliance'),
('E02a','A:Alliance'),
('E03','A:Alliance'),
('E03a','A:Alliance'),
('E04','A:Alliance'),
('E04a','A:Alliance'),
('E05','A:Alliance'),
('E05a','A:Alliance'),
('E06','B:Altération/dévoiement de la réalité'),
('E06a','B:Altération/dévoiement de la réalité'),
('E06a1','B:Altération/dévoiement de la réalité'),
('E07','C: Chantage affectif, loyauté, manipulation'),
('E08','C: Chantage affectif, loyauté, manipulation'),
('E9','C: Chantage affectif, loyauté, manipulation'),
('E10','C: Chantage affectif, loyauté, manipulation'),
('E11','C: Chantage affectif, loyauté, manipulation'),
('E12','D: Dénigrement'),
('E13','D: Dénigrement'),
('E14','D: Dénigrement'),
('E14a','D: Dénigrement'),
('E15','D: Dénigrement'),
('E15a','D: Dénigrement'),
('E16','E: Interférence temps et/ou communication'),
('E16a','E: Interférence temps et/ou communication'),
('E16b','E: Interférence temps et/ou communication'),
('E16c','E: Interférence temps et/ou communication'),
('E18','E: Interférence temps et/ou communication'),
('E20','F: Interférence lien affectif ou symbolique'),
('E21','F: Interférence lien affectif ou symbolique'),
('E21a','F: Interférence lien affectif ou symbolique'),
('E22','F: Interférence lien affectif ou symbolique'),
('E22a','F: Interférence lien affectif ou symbolique'),
('E17','G: Parentification'),
('E23','G: Parentification'),
('E24','G: Parentification'),
('E25','G: Parentification'),
('E26','H: Rôle actif, Réponse au CC, r'),
('E27','H: Rôle actif, Réponse au CC, r'),
('E27a','H: Rôle actif, Réponse au CC, r'),
('E27b','H: Rôle actif, Réponse au CC, r'),
('E28','H: Rôle actif, Réponse au CC, r'),
('E29','H: Rôle actif, Réponse au CC, r'),
('E29a','H: Rôle actif, Réponse au CC, r'),
('E30','H: Rôle actif, Réponse au CC, r'),
('E31','H: Rôle actif, Réponse au CC, r'),
('E32','H: Rôle actif, Réponse au CC, r'),
('E33','H: Rôle actif, Réponse au CC, r'),
('E33a','H: Rôle actif, Réponse au CC, r'),
('E33b','H: Rôle actif, Réponse au CC, r'),
('E34','H: Rôle actif, Réponse au CC, r'),
('E35','H: Rôle actif, Réponse au CC, r'),
('E35a','H: Rôle actif, Réponse au CC, r'),
('E36','H: Rôle actif, Réponse au CC, r'),
('E36a','H: Rôle actif, Réponse au CC, r'),
('E36b','H: Rôle actif, Réponse au CC, r'),
('PCR17','D: Dénigrement'),
('PCR18','D: Dénigrement'),
('NC01','A:Alliance'),
('NC01a','A:Alliance'),
('NC02','B:Altération/dévoiement de la réalité'),
('NC03','C: Chantage affectif, loyauté, manipulation'),
('NC04','D: Dénigrement'),
('NC05','D: Dénigrement'),
('NC06','D: Dénigrement'),
('NC07','E: Interférence temps et/ou communication'),
('NC08','E: Interférence temps et/ou communication'),
('NC09','E: Interférence temps et/ou communication'),
('NC10','E: Interférence temps et/ou communication'),
('NC11','E: Interférence temps et/ou communication'),
('NC12','E: Interférence temps et/ou communication'),
('NC13','E: Interférence temps et/ou communication'),
('NC14','F: Interférence lien affectif ou symbolique'),
('NC15','F: Interférence lien affectif ou symbolique'),
('NC16','H: Rôle actif, Réponse au CC, r'),
('B09','N / A'),
('B10','N / A'),
('B10a','N / A');
