update question set title = "Ces difficultés relationnelles sont-elles récentes?" where question_id = 'B11c2';
update question set title = "Est-ce qu'il y a d'autres enfants en rupture de lien ou de contact?" where question_id = 'B11c3';
update question set title = "Durant la vie commune avec l'autre parent (coparent), quel était le degré de complicité entre vous et votre enfant?" where question_id = 'H01';
update question set title = "Dans quelle mesure acceptez-vous que les vêtements et/ou jouets de votre enfant se promènent d’une maison à l’autre ?" where question_id = 'PCR11';
update question set title = "Dans quelle mesure diriez-vous qu'il est important que votre enfant soit au courant des enjeux de la séparation et/ou du conflit qui vous oppose à l'autre parent ?" where question_id = 'PCR15';
update question set title = "Au-delà des conflits, dans quelle mesure acceptez-vous et êtes-vous serein·e avec la séparation (séparation de couple ou familiale)?" where question_id = 'PCR16';
update question set title = "Est-ce que votre nouveau ou nouvelle conjoint·e corrige votre enfant lorsqu’il est irrespectueux envers vous?" where question_id = 'PCR17';
update question set title = "Est-ce que votre situation crée certains ou d'importants désaccords entre vous et votre nouveau ou nouvelle conjoint·e face à la façon d’agir avec votre enfant?" where question_id = 'PCR18';
update question set title = "Dans quelle mesure diriez-vous que l'autre parent modifie certains faits (historiques) concernant votre passé à son avantage ou à votre désavantage?" where question_id = 'PFA06';
update question set title = "Dans quelle mesure l'autre parent présente aux autres une vision négative de vos comportements ou de votre santé mentale et compétences parentales." where question_id = 'PFA13c';
update question set title = "Arrive-t-il que l’autre parent dénigre ouvertement votre nouvelle famille devant votre enfant? (dénigrement du nouveau ou nouvelle conjoint·e et/ou enfant(s) né(s) d’une nouvelle union)" where question_id = 'PFA14';
update question set title = "Dans quelle mesure diriez-vous que l'autre parent laisse entendre qu'il ou elle représente la 'vraie' famille de votre enfant?" where question_id = 'PFA15';
update question set title = "Arrive-t-il que l’autre parent organise des activités amusantes, voire irrésistibles à votre enfant alors que c’est votre week-end ou votre semaine avec votre enfant?" where question_id = 'PFA16b1';
update question set title = "Comment évalueriez-vous la facilité à communiquer avec votre enfant lorsqu’il est chez l’autre parent?" where question_id = 'PFA20';
update question set title = "Cette façon de s'adresser à vous devant votre enfant (prénom versus maman ou papa), est-elle habituelle ou est-ce nouveau depuis la séparation?" where question_id = 'PFA25a';
update question set title = "Dans quelle mesure diriez-vous que l’autre parent cherche à limiter les contacts entre votre enfant et votre famille élargie (cousin.es, oncles, tantes, grands-parents, etc.)?" where question_id = 'PFA27';
update question set title = "Dans quelle mesure cet énoncé s'applique à votre situation ? L’autre parent permet à votre enfant d'apporter des objets (jouets ou objets symboliques) ou cadeaux reçus provenant de chez vous?" where question_id = 'PFA28';
update question set title = "Dans quelle mesure diriez-vous que l'autre parent encourage ou entretient un discours dénigrant ou haineux à l’égard de votre nouveau ou nouvelle conjoint·e?" where question_id = 'PFA33';
update question set title = "Évaluez la fréquence ou l'intensité de l'énoncé : votre enfant croit que vous souffrez d’une maladie mentale ou que vous êtes instable psychologiquement." where question_id = 'E06a';
update question set title = "Évaluez l'intensité et/ou la fréquence de l'énoncé : votre enfant subit une pression pour passer plus de temps chez l'autre parent." where question_id = 'E16c';
update question set title = "Dans quelle mesure diriez-vous que votre enfant connait des informations personnelles ou intimes de vous dont vous n'avez jamais discuté avec lui?" where question_id = 'E22';
update question set title = "Dans quelle mesure êtes-vous d'accord avec l'énoncé suivant? L'autre parent (coparent) a informé votre enfant du contexte juridique, financier et autres associé au conflit vous opposant." where question_id = 'E24';
update question set title = "Dans quelle mesure votre enfant s'isole (ex.: chambre) ou se cache (ex.: toilettes) pour appeler son autre parent afin qu'on n'entende pas ses conversations?" where question_id = 'E28';
update question set title = "Évaluez la fréquence et l'intensité de l'énoncé : votre enfant vous accuse de mentir, de voler, etc." where question_id = 'E32';
update question set title = "Comment était la relation de votre enfant avec la famille élargie avant la séparation?" where question_id = 'E35a';
update question set title = "Est-ce que votre enfant présente des troubles psychosomatiques en ce moment?" where question_id = 'E36';
update question set title = "Au retour d’un séjour chez l’autre parent, il arrive à votre enfant d'être agressif envers vous et de vous accabler de reproches. Comment réagissez-vous ?" where question_id = 'PCR17';
update question set title = "Si votre enfant vous accuse de mentir, de voler l'argent de l'autre parent, etc. Comment réagissez-vous ?" where question_id = 'PCR18';
update question set title = "Dans quelle mesure le nouveau ou nouvelle conjoint·e interdit aux personnes gravitant autour de votre enfant (professeurs, éducateurs, medecins, entraîneurs, etc.) de vous communiquer de l'information au sujet de votre enfant?" where question_id = 'NC13';
update question set title = "Dans quelle mesure cet énoncé s'applique à votre situation? Le nouveau ou nouvelle conjoint·e demande à votre enfant de l'appeler maman ou papa." where question_id = 'NC14';
update question set title = "Dans quelle mesure cet énoncé s'applique à votre situation? Votre relation avec votre enfant est fragilisée depuis l'arrivée du nouveau ou nouvelle conjoint·e." where question_id = 'NC15';
